---
title: "model"
author: "Ernesto Herrero"
date: "11/28/2021"
output: html_document
---

```{r setup, include=FALSE}

library(tidyverse)

tblx = read_csv("final_project_data.csv")
tbl2 = read_csv("bret-2.csv")
tbl = cbind(tbl1, tbl2)
tbl1 = tblx[,-1]
```


```{r}

```

```{r}
calc_returns1 <- function(which_asset, number, dataset) {
    idx = as.integer(rownames(dataset))
    rbmax = pmax((idx - number), 1)
    rb = (dataset[,which_asset] - dataset[rbmax,which_asset])/dataset[rbmax,which_asset]
    return(rbmax)
}


```

```{r}

```

```{r model}
 Asset_1_BRet_3 <-  calc_returns1(2, 3,  tbl1)
  Asset_1_BRet_3 <-  calc_returns1(2, 3,  tbl1)
  Asset_1_BRet_10 <- calc_returns1(2, 10, tbl1)
  Asset_1_BRet_30 <- calc_returns1(2, 30, tbl1)
  Asset_2_BRet_3 <-  calc_returns1(3, 3,  tbl1)
  Asset_2_BRet_10 <- calc_returns1(3, 10, tbl1)
  Asset_2_BRet_30 <- calc_returns1(3, 30, tbl1)
  Asset_3_BRet_3 <-  calc_returns1(4, 3,  tbl1)
  Asset_3_BRet_10 <- calc_returns1(4, 10, tbl1)
  Asset_3_BRet_30 <- calc_returns1(4, 30, tbl1)
  xx <- cbind(Asset_1_BRet_3, Asset_1_BRet_10, Asset_1_BRet_30, Asset_2_BRet_3, 
              Asset_2_BRet_10, Asset_2_BRet_30, Asset_3_BRet_3, Asset_3_BRet_10, 
              Asset_3_BRet_30)
  
  tbl = cbind(tbl1, xx)
  min10 = c(10:524160)
  rep1 <- rep(524160,9)
  min10 <- c(min10,rep1)
  tbl %>% mutate("min10" = min10) -> tbl
  rf10 = (tbl$Asset_1[tbl$min10] - tbl$Asset_1)/tbl$Asset_1
  # creating forward returns
  tbl %>% mutate("rf10" = rf10) -> tbl





```
