---
jupyter:
  jupytext:
    formats: ipynb,Rmd
    text_representation:
      extension: .Rmd
      format_name: rmarkdown
      format_version: '1.2'
      jupytext_version: 1.11.4
  kernelspec:
    display_name: R
    language: R
    name: ir
---

```{r}
library(tidyverse)
```

```{r}
tbl1 = read_csv("final_project_data.csv")
tbl2 = read_csv("bret-1.csv")
tbl = cbind(tbl1, tbl2)
tbl$min10 = pmin((tbl$...1 + 10), 524160)
tbl$rf10 = (tbl$Asset_1[tbl$min10] - tbl$Asset_1)/tbl$Asset_1
#creating data to use and making a forward returns column
```

```{r}
ggplot(tbl) + geom_point(aes(Asset_1, rf10))
```

```{r}
head(tbl)
```

```{r}

```

```{r}
cutoff = floor(nrow(tbl)*.7)
```

```{r}
train = tbl[1:cutoff,]
test = tbl[(cutoff+1):nrow(tbl),]
#splitting data
```

```{r}
mod1 = lm(rf10 ~ Asset_1_BRet_3+Asset_1_BRet_10+Asset_1_BRet_30+Asset_2_BRet_3+Asset_2_BRet_10+Asset_2_BRet_30+Asset_3_BRet_3+Asset_3_BRet_10+Asset_3_BRet_30, train)
```

```{r}
summary(mod1)
#forward returns of asset 1 with backwards returns as features
```

2-3, 2-30, and 3-3 are significant

```{r}
c(cor(predict(mod1, train), train$rf10), cor(predict(mod1, test), test$rf10))
#in sample and out sample correlations
```

```{r}
three_weeks = 60*24*7
```

```{r}
preds = predict(mod1,tbl)
```

```{r}
length(tbl$rf10)
```

```{r}
correlations <- c()
for(i in 1:nrow(tbl)) {
  
  indexes <- max((i-three_weeks), 1)
  
  if(indexes == 1) {
    correlations <- c(correlations, round(cor(tbl$rf10[1:i], preds[1:i]),4))
  }
  
  else{
    
   correlations <- c(correlations, round(cor(tbl$rf10[indexes:i], preds[indexes:i]),4))
  }
  
}
#backward rolling correlations
correlations
```

```{r}
ggplot() + geom_point(aes(tbl$...1, correlations)) + labs(x = "Time", y = "BRC", main = "Backwards Rolling Correlation over time")
```

The correlaton structure is relatively stationary over the year.

```{r}

```
